#!/bin/sh
mkdir -p build-wayland-egl
pushd build-wayland-egl

cmake \
  -DPXCORE_WAYLAND_DISPLAY_READ_EVENTS=OFF \
  -DDISABLE_DEBUG_MODE=ON \
  -DBUILD_PX_TESTS=OFF \
  -DPREFER_SYSTEM_LIBRARIES=ON \
  -DBUILD_RTREMOTE_LIBS=ON \
  -DPXCORE_WAYLAND_EGL=ON \
  -DBUILD_PXSCENE_WAYLAND_EGL=ON \
  -DBUILD_WITH_GL=ON \
  -DBUILD_WITH_WAYLAND=ON \
  -DCMAKE_SKIP_BUILD_RPATH=OFF \
  -DBUILD_WITH_SERVICE_MANAGER=OFF \
  -DBUILD_PXSCENE_SHARED_LIB=OFF \
  -DBUILD_PXSCENE_APP=ON \
  -DCMAKE_CXX_FLAGS="-fno-delete-null-pointer-checks -Wno-deprecated-declarations -Wno-address -DMESA_EGL_NO_X11_HEADERS -O0 -g3 -DPXSCENE_DISABLE_WST_DECODER -UENABLE_EGL_GENERIC" ..
time make -j$(nproc) VERBOSE=1 && echo "ok"
popd
